### PR TITLE
Make Cosmos DB & SQL Pool Deployment Optional

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
This PR will make the deployment of Azure Cosmos DB optional. Users can control via input parameter or checkbox in the portal, whether they want to deploy Cosmos DB as part of the Data Product deployment. Default option in the Portal is false.

### CODE REVIEW

**Comment by marvinbuss** [comment]
Deployment works for me:
image

**Review by andrehass — COMMENTED** [review]
Looks good. I see that Synapse can be included as add on even when choosing to deploy ADF. Did i get this right ?

**Comment by marvinbuss** [comment]
> Looks good. I see that Synapse can be included as add on even when choosing to deploy ADF. Did i get this right ? I will try to test it tomorrow and also update ESA Workshop Labs with this option.
> 
> Thanks

No, it is either Synapse or ADF. You have to choose between the two. I think having both is usually not required. Let me know, if that is the case in some scenarios.

**Comment by andrehass** [comment]
> > Looks good. I see that Synapse can be included as add on even when choosing to deploy ADF. Did i get this right ? I will try to test it tomorrow and also update ESA Workshop Labs with this option.
> > Thanks
> 
> No, it is either Synapse or ADF. You have to choose between the two. I think having both is usually not required. Let me know, if that is the case in some scenarios.

I got confused with the addition of the parameter below. But it overlooked and I understood now this is actually deploying a SQL Pool insider Synapse workspace in case Synapse workspace is selected as processing service. 

| enableSqlPool | Specifies whether an Azure SQL Pool should be deployed inside your Synapse workspace as part of the template. If you selected dataFactory as processingService, leave this value as is. | `true` or `false` |

**Comment by marvinbuss** [comment]
> > > Looks good. I see that Synapse can be included as add on even when choosing to deploy ADF. Did i get this right ? I will try to test it tomorrow and also update ESA Workshop Labs with this option.
> > > Thanks
> > 
> > 
> > No, it is either Synapse or ADF. You have to choose between the two. I think having both is usually not required. Let me know, if that is the case in some scenarios.
> 
> I got confused with the addition of the parameter below. But it overlooked and I understood now this is actually deploying a SQL Pool insider Synapse workspace in case Synapse workspace is selected as processing service.
> 
> | enableSqlPool | Specifies whether an Azure SQL Pool should be deployed inside your Synapse workspace as part of the template. If you selected dataFactory as processingService, leave this value as is. | `true` or `false` |

Correct, you can enable or disable Sql Pool deployment.

**Review by andrehass — APPROVED** [review]
Optional Cosmos deployment worked for me.

**Pull request merged**
